routes/web.php
<?php

use App\Http\Controllers\AssignMachineController;
use App\Http\Controllers\DetagMachineController;
use App\Http\Controllers\GenerateInvoiceController;
use App\Http\Controllers\GenerateInvoicePdfController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IsInvoiceController;
use App\Http\Controllers\MachineDeactivationController;
use App\Http\Controllers\MachinePostContoller;
use App\Http\Controllers\UserDeactivationController;
use App\Http\Controllers\UserPostsController;
use App\Http\Controllers\UserSessionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DatePickerInvoice;
use App\Http\Controllers\InvoicePDFController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ShowSessionController;
use App\Http\Controllers\UserInvoiceController;
use App\Http\Controllers\ShowTaggedMachine;
use App\Http\Controllers\EditSessionRate;

use Illuminate\Support\Facades\Route;


Route::view('/','template.home')->name('home');

// Route::get('admin/dashboard',[HomeController::class, 'adminHome'])
//       ->name('admin-home')
//       ->middleware('is_admin');
//Route::view('/dashboard','admin.dashboard')->name('dashboard');


//dashboard route
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
});

//admin machine routes

Route::resource('machine',MachinePostContoller::class)->except(['destroy']);
Route::get('machine/{id}/delete',[MachineDeactivationController::class, 'edit'])->name('machine-delete');

// admin tag machine routes

Route::get('/assign-machine',[AssignMachineController::class,'create'])->name('assign-machine');
Route::post('/assign-machine', [AssignMachineController::class,'store']);
Route::get('/tagged-machine', [DetagMachineController::class,'create'])->name('detag-machine');
Route::get(
    '/detag-machine/{id}/detag', [DetagMachineController::class, 'edit']
    )->name('delete-detag');
//Route::resource('edit-session-rate',EditTaggedSessionRate::class)->only('edit','update');

Route::resource('user', UserPostsController::class)->except(['destroy']);
Route::get('user/{id}/delete',[UserDeactivationController::class, 'edit'])->name('user-delete');

//admin invoice routes

Route::resource('invoice',IsInvoiceController::class)->only(['index','store','edit','update','show','create']);
Route::resource('date-invoice',DatePickerInvoice::class)->only(['store']);
Route::get('/pdf/{id}', [InvoicePDFController::class, 'createPDF'])->name('create-pdf');
// Route::view('/cards','admin.invoices.cards')->name('cards-payment');
// Route::view('/mobile-banking','admin.invoices.mobileBanking')->name('mobile-banking-payment');
// Route::view('/net-banking','admin.invoices.netBanking')->name('net-banking-payment');

//admin session routes

Route::resource('user-session',UserSessionController::class)->only(['index','edit','update','store']);

//Admin Edit session rate route

Route::resource('edit-rate',EditSessionRate::class)->only(['index','edit','update']);

//show profile route
Route::get('/profile',[ProfileController::class,'profileController'])->name('profile');

//user session Controller
Route::resource('show-session',ShowSessionController::class)->only(['index']);

//user tagged maachine
Route::resource('show-tagged-machine',ShowTaggedMachine::class)->only(['index']);

//user invoice controller
Route::resource('user-invoice',UserInvoiceController::class)->only(['index','store','edit','update','show','create']);

app/Models/Machines.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Machines extends Model
{
    protected $fillable = [
        'machine_no', 'is_active', 'is_delete', 'is_tagged', 'created_by', 'modified_by'
    ];

    public function taggedUsersMachines(){

        return $this->hasMany(TaggedUsersMachines::class);
    }
}

app/Http/Controllers/API/MACHINEController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Resources\MACHINEResource;
use App\Models\Machines;
use Illuminate\Http\Request;

class MACHINEController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $machine= Machines::where('is_delete','NO')->get();
      return response([ 'ceos' => MACHINEResource::collection($machine),
                    'message' => 'Retrieved successfully'], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $data = $request->all();

      $validator = Validator::make($data, [
        'machine_no' => 'required|unique:machines',
      ]);

      if($validator->fails()){
          return response(['error' => $validator->errors(), 'Validation Error']);
      }
      else {
        $machine = new Machines();
        $machine->machine_no = $data->machine_no;
        $machine->is_active = "YES";
        $machine->created_by = Auth::user()->id;
        $machine->save();

      }

//      $ceo = CEO::create($data);

      return response([ 'machine' => new MACHINEResource($machine),
       'message' => 'Created successfully'], 200);


    //  $request->validated();
       //Machines::create($validatedData);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Machines  $machines
     * @return \Illuminate\Http\Response
     */
    public function show(Machines $machines)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Machines  $machines
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Machines $machines)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Machines  $machines
     * @return \Illuminate\Http\Response
     */
    public function destroy(Machines $machines)
    {
        //
    }
}

resources/views/admin/machine/assignMachine.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="margin-top:10%; width:80%">
    <div class="center" style="padding: 20px"> <h1 class="primary-title">Tag Machine User</h1></div>
    <div class="row card" style="padding: 10px">
          <form method="POST"  action="{{ route('assign-machine') }}" class="col s12">
             @csrf

             <div class="row" style="padding-top: 30px">
                 <div class="col s6">
                   <div class="wrap">
                   <label>User Name</label>
                   <select class="select-css" name="user" id="user_id">
                     <option value="" disabled selected>Select</option>
                   @foreach ($users as $user)
                     <option value="{{ $user->id }}">{{ $user->name }}</option>
                   @endforeach
                   </select>
                   @error('name')
                       <p>{{ $message }}</p>
                   @enderror
                   </div>
                 </div>
                 <div class="col s6">
                     <div class="wrap">
                     <label>Machine No.</label>
                     <select class="select-css" name="machine_no" id="machine_id">
                       <option value="" disabled selected>Select</option>
                       @foreach ($machines as $machine)
                         <option value="{{ $machine->id }}">{{ $machine->machine_no }}</option>
                       @endforeach
                     </select>
                     @error('machine_no')
                         <p>{{ $message }}</p>
                     @enderror
                     </div>
                 </div>


                     <!-- <select name="user" id="user_id">

                         <option value="" disabled selected>Select</option>
                       @foreach ($users as $user)
                         <option value="{{ $user->id }}">{{ $user->name }}</option>
                       @endforeach

                     </select>
                     <label>User Name</label>
                     @error('name')
                         <p>{{ $message }}</p>
                     @enderror -->
              </div>

             <div class="row">
                 <div class="input-field col s6">
                     <label for="hourly_session_charge">Hourly session charge : </label>
                     <input type="number" name="hourly_session_charge" value="{{ old('hourly_session_charge')}}" max="999.00">
                     @error('hourly_session_charge')
                         <p>{{ $message }}</p>
                     @enderror
                 </div>
                 <div class="input-field col s6">
                   <div class="wrap">
                    <label>Currency</label>
                   <select class="select-css" name="currency" id="currency">
                     <option value="" disabled selected>Select</option>


                       <option value="BDT">BDT</option>
                       <option value="AED">AED</option>
                       <option value="USD">USD</option>
                   </select>
                   </div>
                   @error('currency')
                       <p>{{ $message }}</p>
                   @enderror
                 </div>
<!--
                     <select name="currency" id="currency">
                       <option value="" disabled selected>Select</option>


                         <option value="BDT">BDT</option>
                         <option value="AED">AED</option>
                         <option value="USD">USD</option>

                     </select>
                     <label>Currency</label> -->
                 </div>
             <div class="row">
                 <div class="col s12">
                     <button type="submit" class="btn">Tag machine</button>
                 </div>
             </div>
         </form>
      </div>
  </div>
</div>
@endauth
@endsection
@section('customJs')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems);
        });
    </script>
@endsection

resources/views/admin/machine/create.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="margin-top:10%">
      <div class="center" style="padding: 20px"> <h1 class="primary-title">Add Machine</h1></div>
      <div class="row card" style="padding:15px">
          <form method="POST"  action="{{ route('machine.store') }}" class="col s12">
             @csrf

             <div class="row">
                 <div class="col s12">
                     <label for="name">Machine No. : </label>
                     <input type="text" name="machine_no" value="{{ old('name')}}">
                     @error('machine_no')
                         <p>{{ $message }}</p>
                     @enderror
                 </div>
             </div>
             <!-- <div class="row">
                 <div class="input-field col s12">
                     <select name="is_active">
                       <option value="" disabled selected>Select</option>
                       <option value="NO"  >NO</option>
                       <option value="YES" >YES</option>
                     </select>
                     <label>Active</label>
                     @error('is_active')
                         <p>{{ $message }}</p>
                     @enderror
                 </div>
             </div> -->
             <div class="row">
                 <div class="col s12">
                     <button type="submit" class="btn">Add new machine</button>
                 </div>
             </div>
         </form>
      </div>
  </div>
</div>

@endauth
@endsection
@section('customJs')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems);
        });
    </script>
@endsection

resources/views/admin/machine/detag.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="margin-top:10%; width:100%">
      <div class="center" style="padding: 20px"> <h1 class="primary-title">Detag Machine</h1></div>
      <div class="row" style="padding: 10px">
        <div class="card col s6 offset-s3">
          <table>
              <thead>
                <tr>
                    <th>User Name</th>
                    <th>Machine No.</th>
                    <th>Active</th>
                    <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($taggedMachines as $tag)
                <tr>
                  @foreach ($users as $user)
                    @php
                        if($tag->user_id == $user->id)
                        {
                            $name = ucwords($user->name);
                            echo"
                            <td>
                                   $name
                            </td>
                            ";
                        }
                    @endphp

                  @endforeach

                  @foreach ($machines as $machine)
                    @php
                        if($tag->machine_id == $machine->id)
                        {
                            echo"
                            <td>
                                   $machine->machine_no
                            </td>
                            ";
                        }
                    @endphp

                  @endforeach
                  <td>{{ $tag->is_active }}</td>
                  <td><a class="btn" href="{{ route('delete-detag', $tag->id) }}">Detag</a></td>
                </tr>
                @empty
                  <tr><td>No machine tagged!!</td></tr>
                @endforelse
              </tbody>
            </table>

        </div>
      </div>
  </div>
</div>

@endauth
@endsection

resources/views/admin/machine/edit.blade.php
@extends('template.layout')

@section('content')
  @guest
   @include('auth.login')
  @endguest
 @auth
 <div class="main-content">
  <div class="container" style="margin-top:10%; width:100%">
    <div class="center" style="padding: 20px"> <h1 class="primary-title">Edit Machine Details</h1></div>
     <div class="row" style="padding:15px">
           <form method="POST"  action="{{ route('machine.update', $machine->id )}}" class="card col s8 offset-s2" style="padding:40px">
              @csrf
              @method('PUT')

              <div class="row">
                  <label for="name">Machine No. : </label>
                      <input type="text" name="machine_no" value="{{ old('name', $machine->machine_no)}}">
                      @error('machine_no')
                          <p>{{ $message }}</p>
                      @enderror
              </div>
              <div class="row">
                  <div>
                    <div class="wrap">
                      <label style="padding-left: 6px">Active</label>
                      <select class="select-css" name="is_active" style="color:#222">
                          <!-- <option value="">Admin:</option> -->
                          <option value="NO"
                              @php
                              echo (old('is_active', $machine->is_active) == 'NO') ? 'selected' : "";
                              @endphp>NO</option>
                          <option value="YES"
                          @php
                          echo (old('is_active', $machine->is_active) == 'YES') ? 'selected' : "";
                          @endphp>YES</option>
                        </select>
                        <?php if (Session::has('error')): ?>
                          <div class="alert alert-danger">


                              {{Session::get('error')}}

                          </div>
                        <?php endif; ?>
                        @error('is_active')
                            <p>{{ $message }}</p>
                        @enderror

                    </div>

                      <!-- <label>Active</label>
                      <select name="is_active">
                        <option value="">Select</option>
                        <option value="NO"
                            @php
                            echo (old('is_active', $machine->is_active) == 'NO') ? 'selected' : "";
                            @endphp>NO</option>
                        <option value="YES"
                        @php
                        echo (old('is_active', $machine->is_active) == 'YES') ? 'selected' : "";
                        @endphp>YES</option>
                      </select>
                      @error('is_active')
                          <p>{{ $message }}</p>
                      @enderror -->
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <button type="submit" class="btn">Update</button>
                  </div>
              </div>
          </form>
       </div>
<div class="row">
  <div id="picker">
    <input id="demo">
    <button id="toggle">Lanuch</button>
  </div>
</div>

  </div>
 </div>
@endauth
@endsection
@section('customJs')
    <script>
    const picker = new WindowDatePicker({
      el: '#picker',
      toggleEl: '#toggle',
      inputEl: '#demo'
       });
        // document.addEventListener('DOMContentLoaded', function() {
        //     var elems = document.querySelectorAll('select');
        //     var instances = M.FormSelect.init(elems);
        // });
    </script>
@endsection

resources/views/admin/machine/index.blade.php
@extends('template.layout')

@section('content')
  @guest
   @include('auth.login')
  @endguest

 @auth
 <div class="main-content">
   <div class="container" style="margin-top:10%; width:100%">
     <div class="center" style="padding: 20px"> <h1 class="primary-title">Machine List</h1></div>
     <div class="row" style="padding:15px">
      <div class="card col s6 offset-s3" style="padding:15px">
        <table>
            <thead>
              <tr>
                  <th style="text-align:center">Machine No.</th>
                  <th style="text-align:center">Active</th>
                  <th style="text-align:center">Actions</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($machines as $machine)
              <tr>
                <td style="text-align:center">
                  <a href=" {{ route('machine.show',[$machine->id]) }} ">
                    {{ $machine->machine_no }}
                  </a>
                </td>
                <td  style="text-align:center">{{ $machine->is_active }}</td>
                <td style="text-align:center"><a class="btn" href="{{ route('machine.edit', ['machine'=>$machine->id]) }}">Edit</a></td>
                <td style="text-align:center"><a class="btn" href="{{ route('machine-delete', $machine->id) }}">Delete</a></td>
              </tr>
              @empty
                <tr><td>No machine included!!</td></tr>
              @endforelse
            </tbody>
          </table>

      </div>
     </div>

   </div>
 </div>
 @endauth
@endsection

resources/views/admin/machine/show.blade.php
@extends('template.layout')

@section('content')
<div class="container">
  @guest
  @include('auth.login')
  @endguest
</div>


@auth
<div class="main-content">
  <div class="container" style="margin-top:10%;width:100%">
  <div class="center" style="padding: 20px"> <h1 class="primary-title">Machine Details</h1></div>
      <div class="row" style="padding:15px">
        <div class="card col s6 offset-s3" style="padding:20px">
          <?php
            $name = ucwords($users->name);
            $tagged_by = ucwords($tagged_by);
            $tagged_with = ucwords($tagged_with);
            $created_atCarb = \Carbon\Carbon::parse( $machine->created_at);
            $created_at = $created_atCarb->format('M d,Y ,h:i A');
            $modified_atCarb = \Carbon\Carbon::parse($machine->updated_at);
            $modified_at = $modified_atCarb->format('M d,Y ,h:i A');

           ?>
          <table>
              <thead>
                <tr>
                  <div class="center" style="padding: 8px"> <h3 class="primary-title">{{ $machine->machine_no }}</h3></div>
                </tr>
              </thead>
              <tbody>
                  <tr>
                      <th>Active</th>
                      <td>{{ $machine->is_active }}</td>
                  </tr>
                  <tr>
                    <th>Created By: </th>
                    <td>{{$name }}</td>
                  </tr>
                  <tr>
                    <th>Created at: </th>
                    <td>{{ $created_at }}</td>
                  </tr>
                  <tr>
                    <th>Modified at: </th>
                    <td>{{ $modified_at }}</td>
                  </tr>
                  <tr>
                    <th>Tagged: </th>
                    <td>{{$machine->is_tagged }}</td>
                  </tr>
                  <tr>
                    <th>Tagged By: </th>
                    <td>{{$tagged_by}}</td>
                  </tr>
                  <tr>
                    <th>Tagged User: </th>
                   <td>{{$tagged_with}}</td>
                  </tr>
              </tbody>
            </table>

        </div>
      </div>
  </div>
</div>

@endauth

@endsection