routes/web.php
<?php

use App\Http\Controllers\AssignMachineController;
use App\Http\Controllers\DetagMachineController;
use App\Http\Controllers\GenerateInvoiceController;
use App\Http\Controllers\GenerateInvoicePdfController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IsInvoiceController;
use App\Http\Controllers\MachineDeactivationController;
use App\Http\Controllers\MachinePostContoller;
use App\Http\Controllers\UserDeactivationController;
use App\Http\Controllers\UserPostsController;
use App\Http\Controllers\UserSessionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DatePickerInvoice;
use App\Http\Controllers\InvoicePDFController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ShowSessionController;
use App\Http\Controllers\UserInvoiceController;
use App\Http\Controllers\ShowTaggedMachine;
use App\Http\Controllers\EditSessionRate;

use Illuminate\Support\Facades\Route;


Route::view('/','template.home')->name('home');

// Route::get('admin/dashboard',[HomeController::class, 'adminHome'])
//       ->name('admin-home')
//       ->middleware('is_admin');
//Route::view('/dashboard','admin.dashboard')->name('dashboard');


//dashboard route
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
});

//admin machine routes

Route::resource('machine',MachinePostContoller::class)->except(['destroy']);
Route::get('machine/{id}/delete',[MachineDeactivationController::class, 'edit'])->name('machine-delete');

// admin tag machine routes

Route::get('/assign-machine',[AssignMachineController::class,'create'])->name('assign-machine');
Route::post('/assign-machine', [AssignMachineController::class,'store']);
Route::get('/tagged-machine', [DetagMachineController::class,'create'])->name('detag-machine');
Route::get(
    '/detag-machine/{id}/detag', [DetagMachineController::class, 'edit']
    )->name('delete-detag');
//Route::resource('edit-session-rate',EditTaggedSessionRate::class)->only('edit','update');

Route::resource('user', UserPostsController::class)->except(['destroy']);
Route::get('user/{id}/delete',[UserDeactivationController::class, 'edit'])->name('user-delete');

//admin invoice routes

Route::resource('invoice',IsInvoiceController::class)->only(['index','store','edit','update','show','create']);
Route::resource('date-invoice',DatePickerInvoice::class)->only(['store']);
Route::get('/pdf/{id}', [InvoicePDFController::class, 'createPDF'])->name('create-pdf');
// Route::view('/cards','admin.invoices.cards')->name('cards-payment');
// Route::view('/mobile-banking','admin.invoices.mobileBanking')->name('mobile-banking-payment');
// Route::view('/net-banking','admin.invoices.netBanking')->name('net-banking-payment');

//admin session routes

Route::resource('user-session',UserSessionController::class)->only(['index','edit','update','store']);

//Admin Edit session rate route

Route::resource('edit-rate',EditSessionRate::class)->only(['index','edit','update']);

//show profile route
Route::get('/profile',[ProfileController::class,'profileController'])->name('profile');

//user session Controller
Route::resource('show-session',ShowSessionController::class)->only(['index']);

//user tagged maachine
Route::resource('show-tagged-machine',ShowTaggedMachine::class)->only(['index']);

//user invoice controller
Route::resource('user-invoice',UserInvoiceController::class)->only(['index','store','edit','update','show','create']);

resources/views/template/home.blade.php
@extends('template.layout')
@section('content')

<div class="hero" style="height: 94vh;">
    <div class="container_content">
        <h1 class="primary-tite"> Machine Handling <br> System </h1>
    </div>
</div>
@endsection

resources/views/template/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Machine Handling System</title>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <link href="dist/css/window-date-picker.css" rel="stylesheet">
    <script src="dist/js/window-date-picker.js"></script>
    <link rel="stylesheet" href="{{ asset('css/materialize.min.css') }}">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">
</head>
<body>
    @include('template.nav')
    <!-- @include('template.sidenav') -->
    @yield('content')

    <!-- <script src="{{ asset('js/materialize.min.js') }}"></script> -->
    @yield('customJs')
</body>
</html>

resources/views/template/nav.blade.php
<!-- <nav class="grey darken-3">
    <div class="container">
        <div class="nav-wrapper">
            <a href="{{route('home')}}" class="brand-logo">Home</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                @guest
                    <li><a href="{{route('login')}}">Log In</a></li>
                @endguest
                @auth
                    <li>
                      <a class="dropdown-trigger grey darken-3" href="#!" data-target="dropdown1">
                        {{ auth()->user()->name }}
                      </a>
                      <ul id="dropdown1" class="dropdown-content grey darken-3">
                         <li><a href="{{ route('profile') }}">Profile</a></li>
                         <li>
                           <form id="formOne" action="{{route('logout')}}" method="post">
                             @csrf
                             <a type="submit" onclick="formOne.submit()" style="color:black; text-align:center;">Logout</a>
                           </form>
                         </li>
                       </ul>
                    </li>
                    </li>
                    <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li>
                  	<form action="{{route('logout')}}" method="post">
                  	  @csrf
                  	  <button type="submit" class="btn grey darken-3">Logout</button>
                  	</form>
                    </li>
                     <li>
                      <a class='dropdown-trigger' href="{{ route('profile') }}" data-target='dropdown1'>Drop Me!</a>

                      <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="#!">one</a></li>
                      </ul>
                   </li>
                @endauth
            </ul>
        </div>
    </div> -->

<input type="checkbox" id="nav-toggle">
<div class="sidebar">
  <div class="sidebar-brand">
    <h2>
      <span class="lab la-accusoft"></span>
      <span>Machine Manage</span>
    </h2>
  </div>
  <div class="sidebar-menu">
    <ul>
      <li>
        <a href="{{ route('dashboard') }}" class="active">
          <span class="las la-igloo"></span>
          <span>Dashboard</span>
        </a>
      </li>
      <li>
        <a href="{{ route('profile') }}">
          <span class="las la-user"></span>
          <span>Profile</span>
        </a>
      </li>
      <li>
        <a href="{{route('user.create')}}">
          <span class="las la-user-plus"></span>
          <span>Add User</span>
        </a>
      </li>
      <li>
        <a href="{{route('machine.create')}}">
          <span class="las la-laptop"></span>
          <span>Add Machine</span>
        </a>
      </li>
      <li>
        <a href="{{route('user.index')}}">
          <span class="las la-users"></span>
          <span>User List</span>
        </a>
      </li>
      <li>
        <a href="{{route('machine.index')}}">
          <span class="las la-microchip"></span>
          <span>Machine List</span>
        </a>
      </li>
      <li>
        <a href="{{route('assign-machine')}}">
          <span class="las la-tags"></span>
          <span>Tag Machine User</span>
        </a>
      </li>
      <li>
        <a href="{{route('detag-machine')}}">
          <span class="las la-cut"></span>
          <span>Detag Machine</span>
        </a>
      </li>
      <li>
        <a href="{{route('user-session.index')}}">
          <span class="las la-chart-line">
          </span>
          <span>Create Session</span>
        </a>
      </li>
      <li>
        <a href="{{route('edit-rate.index')}}">
          <span class="las la-edit">
          </span>
          <span>Edit Session Rate</span>
        </a>
      </li>
      <li>
        <a href="{{route('invoice.index')}}">
          <span class="las la-clipboard">
          </span>
          <span>Create Invoice</span>
        </a>
      </li>
      <li>
        <a href="{{route('invoice.show',1)}}">
          <span class="las la-chart-bar">
          </span>
          <span>Show Invoice</span>
        </a>
      </li>

    </ul>
  </div>
</div>
<div class="main-content">
  <header>
    <h5>
      <label for="nav-toggle">
        <span class="las la-bars"></span>
      </label>
      Dashboard
    </h5>

    <!-- <div class="search-wrapper">
      <span class="las la-search"></span>
      <input type="search" placeholder="search here">
    </div> -->


@auth
    <div class="user-wrapper">
      <img src="/img/profile.jpg"
      width="50px" height="50px" alt="">
      <div>
          <h6 style="color:black">{{ auth()->user()->name }} {{ auth()->user()->last_name }}</h6>
          <form id="formOne" action="{{route('logout')}}" method="post">
            @csrf
            <!-- <button type="submit">Logout</button> -->
            <a type="submit" onclick="formOne.submit()" style="color:black; text-align:center;">Logout</a>
          </form>
          <!-- <small>Logout</small> -->
      </div>

    </div>
@endauth
  </header>
</div>


<!-- sidenave code pink one     -->
    <!-- <div id="mainbox" onclick="openfunction()">&#9776;</div>
    <div id="menu" class="sidemenu">
      <a href="#">Profile</a>
      <a href="#">Dashboard</a>
      <a href="#">Add User</a>
      <a href="#">Add Machine</a>
      <a href="#">User list</a>
      <a href="#">Machine list</a>
      <a href="#">Tag Machine User</a>
      <a href="#">Detag Machine User</a>
      <a href="#">Create Session</a>
      <a href="#">Edit Session Rate</a>
      <a href="#">Create Invoice</a>
      <a href="#">Show Invoice</a>
      <a href="#" class="closebtn" onclick="closefunction()">x</a>
    </div> -->

<!-- </nav> -->
<!-- <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.dropdown-trigger');
      var instances = M.Dropdown.init(elems);
    });
    function openfunction(){
      document.getElementById("menu").style.width="260px";
      document.getElementById("mainbox").style.marginleft="260px";
    }
    function closefunction(){
      document.getElementById("menu").style.width="0px";
      document.getElementById("mainbox").style.marginleft="0px";
    }


</script> -->

resources/views/template/sidenav.blade.php
    <div id="mainbox" onclick="openfunction()">&#9776;</div>
    <div id="menu" class="sidemenu">
      <a href="#">profile</a>
      <a href="#">Dashboard</a>
      <a href="#" class="closebtn" onclick="closefunction()">$times;</a>
    </div>
<script type="text/javascript">
function openfunction(){
  document.getElementById("menu").style.width="300px";
  document.getElementById("mainbox").style.marginleft="300px";
}
function closefunction(){
  document.getElementById("menu").style.width="0px";
  document.getElementById("mainbox").style.marginleft="0px";
}

</script>