routes/web.php
<?php

use App\Http\Controllers\AssignMachineController;
use App\Http\Controllers\DetagMachineController;
use App\Http\Controllers\GenerateInvoiceController;
use App\Http\Controllers\GenerateInvoicePdfController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IsInvoiceController;
use App\Http\Controllers\MachineDeactivationController;
use App\Http\Controllers\MachinePostContoller;
use App\Http\Controllers\UserDeactivationController;
use App\Http\Controllers\UserPostsController;
use App\Http\Controllers\UserSessionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DatePickerInvoice;
use App\Http\Controllers\InvoicePDFController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ShowSessionController;
use App\Http\Controllers\UserInvoiceController;
use App\Http\Controllers\ShowTaggedMachine;
use App\Http\Controllers\EditSessionRate;

use Illuminate\Support\Facades\Route;


Route::view('/','template.home')->name('home');

// Route::get('admin/dashboard',[HomeController::class, 'adminHome'])
//       ->name('admin-home')
//       ->middleware('is_admin');
//Route::view('/dashboard','admin.dashboard')->name('dashboard');


//dashboard route
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
});

//admin machine routes

Route::resource('machine',MachinePostContoller::class)->except(['destroy']);
Route::get('machine/{id}/delete',[MachineDeactivationController::class, 'edit'])->name('machine-delete');

// admin tag machine routes

Route::get('/assign-machine',[AssignMachineController::class,'create'])->name('assign-machine');
Route::post('/assign-machine', [AssignMachineController::class,'store']);
Route::get('/tagged-machine', [DetagMachineController::class,'create'])->name('detag-machine');
Route::get(
    '/detag-machine/{id}/detag', [DetagMachineController::class, 'edit']
    )->name('delete-detag');
//Route::resource('edit-session-rate',EditTaggedSessionRate::class)->only('edit','update');

Route::resource('user', UserPostsController::class)->except(['destroy']);
Route::get('user/{id}/delete',[UserDeactivationController::class, 'edit'])->name('user-delete');

//admin invoice routes

Route::resource('invoice',IsInvoiceController::class)->only(['index','store','edit','update','show','create']);
Route::resource('date-invoice',DatePickerInvoice::class)->only(['store']);
Route::get('/pdf/{id}', [InvoicePDFController::class, 'createPDF'])->name('create-pdf');
// Route::view('/cards','admin.invoices.cards')->name('cards-payment');
// Route::view('/mobile-banking','admin.invoices.mobileBanking')->name('mobile-banking-payment');
// Route::view('/net-banking','admin.invoices.netBanking')->name('net-banking-payment');

//admin session routes

Route::resource('user-session',UserSessionController::class)->only(['index','edit','update','store']);

//Admin Edit session rate route

Route::resource('edit-rate',EditSessionRate::class)->only(['index','edit','update']);

//show profile route
Route::get('/profile',[ProfileController::class,'profileController'])->name('profile');

//user session Controller
Route::resource('show-session',ShowSessionController::class)->only(['index']);

//user tagged maachine
Route::resource('show-tagged-machine',ShowTaggedMachine::class)->only(['index']);

//user invoice controller
Route::resource('user-invoice',UserInvoiceController::class)->only(['index','store','edit','update','show','create']);

resources/views/userView/showTaggedMachine.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="margin-top:10%; width:80%">
      <div class="center" style="padding: 20px"> <h2 class="primary-title">Tagged Machines</h2></div>
      <div class="row">
        <div class="card col s6 offset-s3">
          <table>
              <thead>
                <tr>
                    <!-- <th>User Name</th> -->
                    <th>Machine No.</th>
                    <th>Session Rate</th>
                    <th>Tagged Date</th>
                    <th>Active</th>
                    <!-- <th>Actions</th> -->
                    <th></th>
                </tr>
              </thead>
              <tbody>
                @forelse ($taggedMachines as $tag)
                <tr>

                  @foreach ($machines as $machine)
                    @php
                        if($tag->machine_id == $machine->id)
                        {
                            echo"
                            <td>
                                   $machine->machine_no
                            </td>

                            ";
                        }
                    @endphp

                  @endforeach

                  <?php
                    $created_at = $tag->created_at;
                    $created_atF = $created_at->format('D, jS F Y');
                   ?>
                  <td>{{$tag->hourly_session_charge}}  {{$tag->currency}}</td>
                  <td>{{$created_atF}}</td>
                  <td>{{ $tag->is_active }}</td>
                  <!-- <td><a class="btn" href="{{ route('delete-detag', $tag->id) }}">Detag</a></td>
                  <td><a class="btn" href="#">Edit Session Rate</a></td> -->
                </tr>
                @empty
                  <tr><td>No machine tagged!!</td></tr>
                @endforelse
              </tbody>
            </table>
        </div>
      </div>
  </div>

</div>
@endauth
@endsection

resources/views/userView/userDashboard.blade.php
@extends('template.layout')
@section('content')
    <!-- <div class="container"> -->
@guest
 @include('auth.login')
@endguest
@auth
 <div class="main-content">
   <main>
     <div class="cards">
       <a href="{{route('profile')}}">
        <div class="card-single">
          <div>
            <h4>Show</h4>
            <span>Profile</span>
          </div>
          <div>
            <span class="las la-user"></span>
          </div>
        </div>
       </a>
       <a href="{{route('show-tagged-machine.index')}}">
        <div class="card-single">
          <div>
            <h4>Tagged</h4>
            <span>Machines</span>
          </div>
          <div>
            <span class="las la-microchip"></span>
          </div>
        </div>
       </a>
       <a href="{{route('user-invoice.index')}}">
        <div class="card-single">
          <div>
            <h4>Create</h4>
            <span>Invoice</span>
          </div>
          <div>
            <span class="las la-clipboard"></span>
          </div>
        </div>
       </a>
       <a href="{{route('user-invoice.show',1)}}">
        <div class="card-single">
          <div>
            <h4>Show</h4>
            <span>Invoice</span>
          </div>
          <div>
            <span class="las la-chart-bar"></span>
          </div>
        </div>
       </a>
     </div>
   </main>
 </div>


        <!-- <div class="row" style="padding-top: 12%">
            <div class="col s6">
                <div class="card-panel blue darken-4" style="background: linear-gradient(180deg,#0d47a1,#1a237e);">
                    <div class="card-action">
                        <a class="white-text" href="{{route('profile')}}">profile</a>
                    </div>
                </div>
            </div>
            <div class="col s6">
                <div class="card-panel yellow darken-4" style="background: linear-gradient(180deg,#ff6f00,#ff6f00 );">
                    <div class="card-action">
                        <a class="white-text" href="{{route('show-tagged-machine.index')}}">Tagged Machines</a>
                    </div>
                </div>
            </div>
          </br></br>
            <div class="col s6">
                <div class="card-panel deep-orange darken-4" style="background: linear-gradient(180deg,#dd2c00,#bf360c );">
                    <div class="card-action">
                        <a class="white-text" href="{{route('user-invoice.index')}}">Create Invoice</a>
                    </div>
                </div>
            </div>
            <div class="col s6">
                <div class="card-panel green darken-4" style="background: linear-gradient(180deg,#33691e,#1b5e20 );">
                    <div class="card-action">
                        <a class="white-text" href="{{route('user-invoice.show',1)}}">My Invoices</a>
                    </div>
                </div>
            </div>
        </div> -->
@endauth
    <!-- </div> -->

@endsection