routes/web.php
<?php

use App\Http\Controllers\AssignMachineController;
use App\Http\Controllers\DetagMachineController;
use App\Http\Controllers\GenerateInvoiceController;
use App\Http\Controllers\GenerateInvoicePdfController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IsInvoiceController;
use App\Http\Controllers\MachineDeactivationController;
use App\Http\Controllers\MachinePostContoller;
use App\Http\Controllers\UserDeactivationController;
use App\Http\Controllers\UserPostsController;
use App\Http\Controllers\UserSessionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DatePickerInvoice;
use App\Http\Controllers\InvoicePDFController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ShowSessionController;
use App\Http\Controllers\UserInvoiceController;
use App\Http\Controllers\ShowTaggedMachine;
use App\Http\Controllers\EditSessionRate;

use Illuminate\Support\Facades\Route;


Route::view('/','template.home')->name('home');

// Route::get('admin/dashboard',[HomeController::class, 'adminHome'])
//       ->name('admin-home')
//       ->middleware('is_admin');
//Route::view('/dashboard','admin.dashboard')->name('dashboard');


//dashboard route
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
});

//admin machine routes

Route::resource('machine',MachinePostContoller::class)->except(['destroy']);
Route::get('machine/{id}/delete',[MachineDeactivationController::class, 'edit'])->name('machine-delete');

// admin tag machine routes

Route::get('/assign-machine',[AssignMachineController::class,'create'])->name('assign-machine');
Route::post('/assign-machine', [AssignMachineController::class,'store']);
Route::get('/tagged-machine', [DetagMachineController::class,'create'])->name('detag-machine');
Route::get(
    '/detag-machine/{id}/detag', [DetagMachineController::class, 'edit']
    )->name('delete-detag');
//Route::resource('edit-session-rate',EditTaggedSessionRate::class)->only('edit','update');

Route::resource('user', UserPostsController::class)->except(['destroy']);
Route::get('user/{id}/delete',[UserDeactivationController::class, 'edit'])->name('user-delete');

//admin invoice routes

Route::resource('invoice',IsInvoiceController::class)->only(['index','store','edit','update','show','create']);
Route::resource('date-invoice',DatePickerInvoice::class)->only(['store']);
Route::get('/pdf/{id}', [InvoicePDFController::class, 'createPDF'])->name('create-pdf');
// Route::view('/cards','admin.invoices.cards')->name('cards-payment');
// Route::view('/mobile-banking','admin.invoices.mobileBanking')->name('mobile-banking-payment');
// Route::view('/net-banking','admin.invoices.netBanking')->name('net-banking-payment');

//admin session routes

Route::resource('user-session',UserSessionController::class)->only(['index','edit','update','store']);

//Admin Edit session rate route

Route::resource('edit-rate',EditSessionRate::class)->only(['index','edit','update']);

//show profile route
Route::get('/profile',[ProfileController::class,'profileController'])->name('profile');

//user session Controller
Route::resource('show-session',ShowSessionController::class)->only(['index']);

//user tagged maachine
Route::resource('show-tagged-machine',ShowTaggedMachine::class)->only(['index']);

//user invoice controller
Route::resource('user-invoice',UserInvoiceController::class)->only(['index','store','edit','update','show','create']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;
    use Notifiable, HasApiTokens; // update this line

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'name',
      'first_name',
      'last_name',
      'company_name',
      'phone_number',
      'address',
      'tax_reg_no',
      'role_id',
      'bank_account_type',
      'web_site',
      'email',
      'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function taggedUsersMachines(){

        return $this->hasMany(TaggedUsersMachines::class);
    }
}

resources/views/admin/user/create.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="margin-top:10%">
     <div class="center" style="padding: 20px"> <h1 class="primary-title">Add User</h1></div>
      <div class="row card" style="padding:8px">
          <form class="col s12" method="POST" action="{{route('user.store')}}">
              @csrf
              <div class="row">
                  <div class="col s6">
                      {{-- Frist Name Start --}}
                      <label for="first_name">First Name : </label>
                      <input type="text" name="first_name" value="{{ old('first_name')}}">
                      @error('first_name')
                          <p>{{ $message }}</p>
                      @enderror
                      {{-- First Name End --}}
                  </div>
                  <div class="col s6">
                      {{-- Last Name Start --}}
                      <label for="last_name">Last Name : </label>
                      <input type="text" name="last_name" value="{{ old('last_name')}}">
                      @error('last_name')
                          <p>{{ $message }}</p>
                      @enderror
                      {{-- Last Name End --}}
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="name">Name : </label>
                      <input type="text" name="name" value="{{ old('name')}}">
                      @error('name')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="email">E-mail : </label>
                      <input type="text" name="email" value="{{ old('email')}}">
                      @error('email')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="company_name">Company Name : </label>
                      <input type="text" name="company_name" value="{{ old('company_name')}}">
                      @error('company_name')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="phone_number">Phone Number : </label>
                      <input type="number" name="phone_number" value="{{ old('phone_number')}}">
                      @error('phone_number')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="address">Address : </label>
                      <textarea name="address" id="address_id" class="materialize-textarea" ></textarea>
                      @error('address')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="tax_reg_no">Tax Registration Number : </label>
                      <input type="number" name="tax_reg_no" value="{{ old('tax_reg_no')}}">
                      @error('tax_reg_no')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="bank_account_type">Bank Account Type : </label>
                      <input type="text" name="bank_account_type" value="{{ old('bank_account_type')}}">
                      @error('bank_account_type')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="web_site">Web Site Address : </label>
                      <input type="text" name="web_site" value="{{ old('web_site')}}">
                      @error('web_site')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                <div class="input-field">
                  <div class="wrap">
                  <select class="select-css" name="role_id">
                      <option value="">Regiister As:</option>
                      <option value="2"  >User</option>
                      <option value="1" >Admin</option>
                  </select>
                  </div>
                  @error('role_id')
                      <p>{{ $message }}</p>
                  @enderror

                </div>
              </div>

              <!-- <div class="row">
                  <div class="col s12">
                      <select name="role_id">
                        <option value="" disabled selected>Select</option>
                        <option value="2"  >User</option>
                        <option value="1" >Admin</option>
                      </select>
                      <label>Register as:</label>
                      @error('role_id')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div> -->
              <!-- <div class="row">
                  <div class="input-field col s12">
                      <select name="is_active">
                        <option value="" disabled selected>Select</option>
                        <option value="NO"  >NO</option>
                        <option value="YES" >YES</option>
                      </select>
                      <label>Active</label>
                      @error('is_active')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div> -->

              <div class="row">
                  <div class="col s12">
                      <label for="password">Password : </label>
                      <input type="password" name="password">
                      @error('password')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="password_confirmed">Retype Password : </label>
                      <input type="password" name="password_confirmation">
                      @error('password')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <button type="submit" class="btn">Add new user</button>
                  </div>
              </div>
          </form>
      </div>
  </div>

</div>

@endauth
@endsection
@section('customJs')
<script>
$(document).ready(function(){
    $('select').formSelect();
  })
</script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="margin-top:10%; width:100%">
    <div class="center" style="padding: 20px"> <h1 class="primary-title">Edit User Details</h1></div>
        <div class="row card" style="padding:30px">
          <form class="col s12" method="POST" action="{{route('user.update', $userPost->id)}}">
              @csrf
              @method('PUT')

              <div class="row">
                  <div class="col s6">
                      {{-- Frist Name Start --}}
                      <label for="first_name">First Name : </label>
                      <input type="text" name="first_name" value="{{ old('first_name', $userPost->first_name)}}">
                      @error('first_name')
                          <p>{{ $message }}</p>
                      @enderror
                      {{-- First Name End --}}
                  </div>
                  <div class="col s6">
                      {{-- Last Name Start --}}
                      <label for="last_name">Last Name : </label>
                      <input type="text" name="last_name" value="{{ old('last_name', $userPost->last_name)}}">
                      @error('last_name')
                          <p>{{ $message }}</p>
                      @enderror
                      {{-- Last Name End --}}
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="name">Name : </label>
                      <input type="text" name="name" value="{{ old('name', $userPost->name)}}">
                      @error('name')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>

              <div class="row">
                  <div class="col s12">
                      <label for="company_name">Company Name : </label>
                      <input type="text" name="company_name" value="{{ old('company_name', $userPost->company_name)}}">
                      @error('company_name')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="email">Email : </label>
                      <input type="text" name="email" value="{{ old('email', $userPost->email)}}">
                      @error('email')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="phone_number">Phone Number : </label>
                      <input type="number" name="phone_number" value="{{ old('phone_number', $userPost->phone_number)}}">
                      @error('phone_number')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="address">Address : </label>
                      <textarea name="address" id="address_id" class="materialize-textarea">{{ old('address', $userPost->address)}}</textarea>
                      @error('address')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="tax_reg_no">Tax Registration Number : </label>
                      <input type="number" name="tax_reg_no" value="{{ old('tax_reg_no', $userPost->tax_reg_no)}}">
                      @error('tax_reg_no')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="bank_account_type">Bank Account Type : </label>
                      <input type="text" name="bank_account_type" value="{{ old('bank_account_type', $userPost->bank_account_type)}}">
                      @error('bank_account_type')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <label for="web_site">Web Site Address : </label>
                      <input type="text" name="web_site" value="{{ old('web_site', $userPost->web_site)}}">
                      @error('web_site')
                          <p>{{ $message }}</p>
                      @enderror
                  </div>
              </div>

              <div class="row">
                  <div>
                    <div class="wrap">
                      <label style="padding-left: 6px">Admin</label>
                      <select class="select-css" name="is_admin" style="color:#222">
                          <!-- <option value="">Admin:</option> -->
                          <option value="NO"
                              @php
                              // ddd(old('is_admin', $userPost->is_admin));
                              echo (old('is_admin', $userPost->is_admin) == 'NO') ? 'selected' : "";
                              @endphp>NO</option>
                          <option value="YES"
                          @php
                          echo (old('is_admin', $userPost->is_admin) == 'YES') ? 'selected' : "";
                          @endphp>YES</option>
                        </select>
                        @error('is_admin')
                            <p>{{ $message }}</p>
                        @enderror

                    </div>

                      <!-- <label style="padding-left: 6px">Admin</label>
                      <select name="is_admin">
                        <option  value="">Select</option>
                        <option value="NO"
                            @php
                            // ddd(old('is_admin', $userPost->is_admin));
                            echo (old('is_admin', $userPost->is_admin) == 'NO') ? 'selected' : "";
                            @endphp>NO</option>
                        <option value="YES"
                        @php
                        echo (old('is_admin', $userPost->is_admin) == 'YES') ? 'selected' : "";
                        @endphp>YES</option>
                      </select>
                      @error('is_admin')
                          <p>{{ $message }}</p>
                      @enderror -->
                  </div>
              </div>
              <div class="row">
                  <div>
                    <div class="wrap">
                      <label style="padding-left: 6px">Active</label>
                      <select class="select-css" name="is_active" style="color:#222">
                          <!-- <option value="">Admin:</option> -->
                          <option value="NO"
                              @php
                              // ddd(old('is_admin', $userPost->is_admin));
                              echo (old('is_active', $userPost->is_active) == 'NO') ? 'selected' : "";
                              @endphp>NO</option>
                          <option value="YES"
                          @php
                          echo (old('is_active', $userPost->is_active) == 'YES') ? 'selected' : "";
                          @endphp>YES</option>
                        </select>
                        @error('is_active')
                            <p>{{ $message }}</p>
                        @enderror

                    </div>

                      <!-- <label>Active</label>
                      <select name="is_active">
                        <option value="">Select</option>
                        <option value="NO"
                            @php
                            // ddd(old('is_admin', $userPost->is_admin));
                            echo (old('is_active', $userPost->is_active) == 'NO') ? 'selected' : "";
                            @endphp>NO</option>
                        <option value="YES"
                        @php
                        echo (old('is_active', $userPost->is_active) == 'YES') ? 'selected' : "";
                        @endphp>YES</option>
                      </select>
                      @error('is_active')
                          <p>{{ $message }}</p>
                      @enderror -->
                  </div>
              </div>
              <div class="row">
                  <div class="col s12">
                      <button type="submit" class="btn">Update</button>
                  </div>
              </div>
          </form>
      </div>
  </div>

</div>

@endauth
@endsection

@section('customJs')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems);
        });
    </script>
@endsection

resources/views/admin/user/index.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="margin-top:10%;width:100%">
    <div class="center" style="padding: 20px"> <h1 class="primary-title">User List</h1></div>
    <div class="row card" style="padding:15px">
      <table>
        <thead>
          <tr>
              <th>Name</th>
              <th>Full Name</th>
              <th>Email</th>
              <th>Phone Number</th>
              <th>Company</th>
              <th>Admin</th>
              <th>Active</th>
              <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($users as $user)
          <tr>
            <td>
              <a href=" {{ route('user.show',['user'=>$user->id]) }} ">
                <?php
                  $userName = ucwords($user->name);
                  $firstName = ucwords($user->first_name);
                  $lastName = ucwords($user->last_name);
                  $companyName = ucwords($user->company_name);
                 ?>
                {{ $userName }}
              </a>
            </td>
            <td>{{$firstName}} {{$lastName}}</td>
            <td>{{$user->email}}</td>
            <td style="text-align:center;">{{$user->phone_number}}</td>
            <td>{{$companyName}}</td>
            <td>{{$user->is_admin}}</td>
            <td>{{ $user->is_active }}</td>
            <td><a class="btn" href="{{ route('user.edit', $user->id) }}">Edit</a></td>
            <td><a class="btn" href="{{ route('user-delete', $user->id) }}">Delete</a></td>
          </tr>
          @empty
            <tr><td>No user added!!</td></tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>

</div>


@endauth
@endsection

resources/views/admin/user/show.blade.php
@extends('template.layout')
@section('content')
@guest
@include('auth.login')
@endguest
@auth
<div class="main-content">
  <div class="container" style="width:80%">
    <div class="center" style="padding: 20px"> <h1 class="primary-title">User Details</h1></div>
        <div class="row" style="padding:15px">
          <div class="card col s6 offset-s3">
            <?php
              $name = ucwords($users->name );
              $lastName = ucwords($users->last_name );
              $firstName = ucwords($users->first_name );
              $companyName = ucwords($users->company_name);
              $accountName = ucwords($users->bank_account_type);
              $created_by = ucwords($created_by);
              $modified_by = ucwords($modified_by);
              $created_atCarb = \Carbon\Carbon::parse( $users->created_at );
              $created_at = $created_atCarb->format('M d,Y ,h:i A');

             ?>
            <table>
                <thead>
                  <tr>
                    <div class="center" style="padding: 8px"> <h3 class="primary-title">{{ $name }}</h3></div>
                  </tr>
                </thead>

                <tbody>
                    <tr>
                        <th>First Name</th>
                        <td>{{ $firstName }}</td>
                    </tr>
                    <tr>
                      <th>Last Name</th>
                      <td>{{ $lastName }}</td>
                    </tr>
                    <tr>
                      <th>Email </th>
                      <td>{{ $users->email }}</td>
                    </tr>
                    <tr>
                      <th>Company name</th>
                      <td>{{ $companyName }}</td>
                    </tr>
                    <tr>
                      <th>Phone Number</th>
                      <td>{{ $users->phone_number }}</td>
                    </tr>
                    <tr>
                      <th>Address</th>
                      <td>{{ $users->address}}</td>
                    </tr>
                    <tr>
                      <th>Web Address</th>
                      <td>{{ $users->web_site }}</td>
                    </tr>
                    <tr>
                      <th>Bank Account</th>
                      <td>{{ $accountName }}</td>
                    </tr>
                    <tr>
                      <th>Admin</th>
                      <td>{{ $users->is_admin }}</td>
                    </tr>
                    <tr>
                      <th>Active</th>
                      <td>{{ $users->is_active }}</td>
                    </tr>
                    <tr>
                      <th>Tagged</th>
                      <td>{{ $users->is_tagged }}</td>
                    </tr>
                    <tr>
                      <th>Created By</th>
                      <td>{{ $created_by }}</td>
                    </tr>
                    <tr>
                      <th>Modified By</th>
                      <td>{{ $modified_by }}</td>
                    </tr>
                    <tr>
                      <th>Created At</th>
                      <td>{{ $created_at }}</td>
                    </tr>
                    <tr>
                      <th>Modifed At</th>
                      <td>{{ $modified_at }}</td>
                    </tr>
                    <tr>
                      <th>Active</th>
                      <td>{{$users->is_active}}</td>
                    </tr>

                  </tbody>

              </table>

          </div>
      </div>
  </div>

</div>

@endauth
@endsection